services:
  web:
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/app
      - ./media:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=wordle_minus.settings
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python scripts/import_countries.py &&
        python manage.py runserver 0.0.0.0:8000
      " 