# Generated by Django 4.2.20 on 2025-04-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='latitude',
            field=models.FloatField(default=1, help_text='Latitude in decimal degrees'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='longitude',
            field=models.FloatField(default=1, help_text='Longitude in decimal degrees'),
            preserve_default=False,
        ),
    ]
