# Generated by Django 4.2.20 on 2025-04-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_country_latitude_country_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='map',
            field=models.ImageField(blank=True, null=True, upload_to='maps/'),
        ),
        migrations.AlterField(
            model_name='country',
            name='continents',
            field=models.ManyToManyField(to='quiz.continent'),
        ),
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.ImageField(upload_to='flags/'),
        ),
        migrations.AlterField(
            model_name='country',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='country',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
