# Generated by Django 5.2 on 2025-04-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_continent_options_alter_continent_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.ImageField(upload_to='country_images/'),
        ),
    ]
